### ISSUE TITLE
Change in output image size from 128 * 128 px to custom size

### ISSUE THREAD

**Issue by imgugale** [Yuheng-Li/MixNMatch#6]
I am trying to train the model on custom dataset. 
The train dataset is of the size 400 * 400 px. But while inferring the size of generated output is 128 * 128 px.

Is it possible to change the size of output image? If yes, is some modification required in the code?

**Comment by Yuheng-Li** [comment]
If you want to change to 400*400. 

**datasets.py**: (1) in get_imgs() change imsize to [0,400]. (2) change my_crop_width into a custom value, which I will explain how to calculate later. If this is not working, then I recommend you first to check what is output from our current dataloader and write your own dataloader. 

**train_first_stage.py**:  (1) change values of self.patch_stride,  self.n_out,  self.recp_field, such that 
recp_field+(n_out-1)*stride = the custom value. These values are tied with the background discriminator. For example, we are using a patch discriminator with recp=34, n_out:24, stide:4, thus our custom value is 126. You need to design your a patch-level background discriminator, and get their recp_field, n_out and stride. (2) change number 126 in L219 and L221 into your custom value.

**model_train.py** : Change architecture of all models: genrerator, background/parent/child discriminator, encoder, bi_discriminator, feature_extracotr such that they can process or generate 400px images. Note that background discriminator architecture determines the values mentioned above. 

**train_second_stage.py**: Since you will modify parent generator, thus you need to change argument in L45, and L49. The current number 16 means number of channels of parent feature(the one fed into child generator), once you change architrcure replace 16 with your number of channels.
